name = "Iron & Arcana"
author = "iron-and-arcana"
version = "2.0.0"
description = "A colony-building, engineering, and exploration pack for a small friend server."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e9872683351f550c9807404309856ae34f1a2230de5b90664bbad6abcd8f1dc"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
