name = "Iron & Arcana"
author = "iron-and-arcana"
version = "2.0.0"
description = "A colony-building, engineering, and exploration pack for a small friend server."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "add7b315924a1810fbd459d210412153e67c40d4bba3c29997ba244148318149"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
