name = "Iron & Arcana"
author = "iron-and-arcana"
version = "2.0.0"
description = "A colony-building, engineering, and exploration pack for a small friend server."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "28d09291779ed9d22db9868b7dab98fa12e9efd9be4b9aceeb65023f576ea2fc"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
